### ISSUE TITLE
Create non-admin tokens

### ISSUE THREAD

**Issue by holmesb** [bitnami/bitnami-docker-influxdb#6]
Hi,

Be great if this docker image could create the read and write users' tokens in the same way as it does for the admin token.  Would mean they'd remain the same between reinstalls.

Many thanks

**Comment by alemorcuq** [comment]
Hi, @holmesb.

Can you give me an example of what you want? Are you referring to the `INFLUXDB_ADMIN_USER_TOKEN` variable?

**Comment by holmesb** [comment]
Hi @alemorcuq, yes can specify an INFLUXDB_ADMIN_USER_TOKEN, but not an INFLUXDB_READ_USER_TOKEN nor INFLUXDB_WRITE_USER_TOKEN

**Comment by alemorcuq** [comment]
I'm going to create an internal task to add support for this. I can't give you an ETA, but feel free to contribute with a PR if you want.

**Comment by fmulero** [comment]
This requests has more than a year and there is no plan to implement it in short term.

We are also moving to [a new repository](https://github.com/bitnami/containers) in order to be aligned with the approach followed in [bitnami/charts](https://github.com/bitnami/charts). More information [here](https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html). If you are still interested on this feature, please open a new issue in [bitnami/containers](https://github.com/bitnami/containers) repository
